name: CI
on: [push]
jobs:
  python-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11.6
        # Health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

      redis:
        image: redis:5.0.8
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Apt update
        run: sudo apt-get update

      - name: Apt install
        run: cat Aptfile | sudo xargs apt-get install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - id: cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/test_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt -r test_requirements.txt

      - name: Lint
        run: pylint ./**/*.py
        env:
          DJANGO_SETTINGS_MODULE: "main.settings.production"
          PYTHONPATH: "."

      - name: Black
        run: black --check .

      - name: Tests
        run: |
          export MEDIA_ROOT="$(mktemp -d)"
          sudo mkdir /var/media
          sudo chown -R $USER:$USER /var/media
          ./scripts/test/python_tests.sh
        env:
          DATABASE_DISABLE_SSL: 'True'
          SECURE_SSL_REDIRECT: 'False'
          CELERY_TASK_ALWAYS_EAGER: 'True'
          CELERY_BROKER_URL: redis://localhost:6379/4
          CELERY_RESULT_BACKEND: redis://localhost:6379/4
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          DEBUG: 'False'
          SECRET_KEY: local_unsafe_key

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true